export const DASHBOARD_MOBILE_TAB_CHANGE = "DASHBOARD_MOBILE_TAB_CHANGE";
export const DASHBOARD_LIST_ACCORDION_TOGGLE = "DASHBOARD_LIST_ACCORDION_TOGGLE";
export const DASHBOARD_ADD_EDIT_DRAWER_TOGGLE = "DASHBOARD_ADD_EDIT_DRAWER_TOGGLE";

export const DASHBOARD_FETCH_LOANS_SUCCESS = "DASHBOARD_FETCH_LOANS_SUCCESS";
export const DASHBOARD_FETCH_LOANS_LOADING = "DASHBOARD_FETCH_LOANS_LOADING";
export const DASHBOARD_FETCH_LOANS_ERROR = "DASHBOARD_FETCH_LOANS_ERROR";

export const DASHBOARD_CREATE_LOAN_SUCCESS = "DASHBOARD_CREATE_LOAN_SUCCESS";
export const DASHBOARD_CREATE_LOAN_LOADING = "DASHBOARD_CREATE_LOAN_LOADING";

export const DASHBOARD_UPDATE_LOAN_SUCCESS = "DASHBOARD_UPDATE_LOAN_SUCCESS";
export const DASHBOARD_UPDATE_LOAN_LOADING = "DASHBOARD_UPDATE_LOAN_LOADING";

export const DASHBOARD_DELETE_LOAN_SUCCESS = "DASHBOARD_DELETE_LOAN_SUCCESS";
export const DASHBOARD_DELETE_LOAN_LOADING = "DASHBOARD_DELETE_LOAN_LOADING";

export const DASHBOARD_FETCH_PAYMENT_PLANS_SUCCESS = "DASHBOARD_FETCH_PAYMENT_PLANS_SUCCESS";
export const DASHBOARD_FETCH_PAYMENT_PLANS_LOADING = "DASHBOARD_FETCH_PAYMENT_PLANS_LOADING";
export const DASHBOARD_FETCH_PAYMENT_PLANS_ERROR = "DASHBOARD_FETCH_PAYMENT_PLANS_ERROR";

export const DASHBOARD_CREATE_PAYMENT_PLANS_SUCCESS = "DASHBOARD_CREATE_PAYMENT_PLANS_SUCCESS";
export const DASHBOARD_CREATE_PAYMENT_PLANS_LOADING = "DASHBOARD_CREATE_PAYMENT_PLANS_LOADING";

export const DASHBOARD_UPDATE_PAYMENT_PLANS_SUCCESS = "DASHBOARD_UPDATE_PAYMENT_PLANS_SUCCESS";
export const DASHBOARD_UPDATE_PAYMENT_PLANS_LOADING = "DASHBOARD_UPDATE_PAYMENT_PLANS_LOADING";

export const DASHBOARD_DELETE_PAYMENT_PLANS_SUCCESS = "DASHBOARD_DELETE_PAYMENT_PLANS_SUCCESS";
export const DASHBOARD_DELETE_PAYMENT_PLANS_LOADING = "DASHBOARD_DELETE_PAYMENT_PLANS_LOADING";
