export const HANDLE_GROUP_BY_CHANGE_SUCCESS = "HANDLE_GROUP_BY_CHANGE_SUCCESS";

export const SCHEDULE_PIVOT_SUCCESS = "SCHEDULE_PIVOT_SUCCESS";
export const SCHEDULE_PIVOT_LOADING = "SCHEDULE_PIVOT_LOADING";
export const SCHEDULE_PIVOT_ERROR = "SCHEDULE_PIVOT_ERROR";
