export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export const USER_SIGN_UP_LOADING = "USER_SIGN_UP_LOADING";
export const USER_SIGN_UP_ERROR = "USER_SIGN_UP_ERROR";

export const USER_SIGN_IN_SUCCESS = "USER_SIGN_IN_SUCCESS";
export const USER_SIGN_IN_LOADING = "USER_SIGN_IN_LOADING";
export const USER_SIGN_IN_ERROR = "USER_SIGN_IN_ERROR";

export const USER_SIGN_OUT_SUCCESS = "USER_SIGN_OUT_SUCCESS";

export const USER_CHANGE_LOCALE_SUCCESS = "USER_CHANGE_LOCALE_SUCCESS";
export const USER_CHANGE_THEME_SUCCESS = "USER_CHANGE_THEME_SUCCESS";

export const DASHBOARD_ADD_EDIT_DRAWER_TOGGLE = "DASHBOARD_ADD_EDIT_DRAWER_TOGGLE";
