export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export const USER_SIGN_UP_LOADING = "USER_SIGN_UP_LOADING";
export const USER_SIGN_UP_ERROR = "USER_SIGN_UP_ERROR";

export const USER_SIGN_IN_SUCCESS = "USER_SIGN_IN_SUCCESS";
export const USER_SIGN_IN_LOADING = "USER_SIGN_IN_LOADING";
export const USER_SIGN_IN_ERROR = "USER_SIGN_IN_ERROR";

export const USER_SIGN_OUT_SUCCESS = "USER_SIGN_OUT_SUCCESS";

export const USER_CHANGE_LOCALE_SUCCESS = "USER_CHANGE_LOCALE_SUCCESS";
export const USER_CHANGE_THEME_SUCCESS = "USER_CHANGE_THEME_SUCCESS";

export const USER_SEND_PASSWORD_RESET_SUCCESS = "USER_SEND_PASSWORD_RESET_SUCCESS";
export const USER_SEND_PASSWORD_RESET_LOADING = "USER_SEND_PASSWORD_RESET_LOADING";
export const USER_SEND_PASSWORD_RESET_ERROR = "USER_SEND_PASSWORD_RESET_ERROR";

export const USER_FETCH_RESET_DETAILS_SUCCESS = "USER_FETCH_RESET_DETAILS_SUCCESS";
export const USER_FETCH_RESET_DETAILS_LOADING = "USER_FETCH_RESET_DETAILS_LOADING";
export const USER_FETCH_RESET_DETAILS_ERROR = "USER_FETCH_RESET_DETAILS_ERROR";

export const USER_SET_NEW_PASSWORD_SUCCESS = "USER_SET_NEW_PASSWORD_SUCCESS";
export const USER_SET_NEW_PASSWORD_LOADING = "USER_SET_NEW_PASSWORD_LOADING";
export const USER_SET_NEW_PASSWORD_ERROR = "USER_SET_NEW_PASSWORD_ERROR";
