on:
  push:
    branches: [ staging ]
    paths: 
      - 'frontend/**'
  pull_request:
    branches: [ staging ]
    paths: 
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'

    - name: npm install, build, and test
      working-directory: ./frontend
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'loan-calculator-client-staging'
        slot-name: 'staging'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2eafa3d1fb8c4b7ba0313d293aaf3130 }}
        package: ./frontend/build
