name: Build and deploy Node.js app to Azure Web App - loan-calculator-client-staging

on:
  push:
    branches: 
      - master
    paths: 
      - 'frontend/**'
  pull_request:
    branches: 
      - master
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'

    - name: npm install, build, and test
      working-directory: 'frontend/'
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
      env:
        REACT_APP_API_BASE_URL: ${{secrets.PRODUCTION_API_HOST}}

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'loan-calculator-production'
        slot-name: 'production'
        publish-profile: ${{ secrets.Production_Client_AzureAppService_PublishProfile }}
        package: 'frontend/build'
